name: fast_testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        tarantool:
          - '1.10'
          - '2.8'
          - '2.10'

    steps:
      - name: Clone the module
        uses: actions/checkout@v2

      - name: Setup tarantool ${{ matrix.tarantool }}
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - run: cmake . && make check
