name: reusable_testing

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The name of the tarantool build artifact'
        default: ubuntu-focal
        required: false
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Clone the queue module'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/queue

      - name: 'Download the tarantool build artifact'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: 'Install tarantool'
        # Now we're lucky: all dependencies are already installed. Check package
        # dependencies when migrating to other OS version.
        run: sudo dpkg -i tarantool*.deb

      - run: cmake . && make check
